package ru.evotor.framework.kkt.provider

import android.net.Uri

object KktContract {
    const val AUTHORITY = "ru.evotor.evotorpos.kkt"
    val BASE_URI: Uri = Uri.parse("content://$AUTHORITY")

    const val COLUMN_SUPPORTED_FFD_VERSION = "SUPPORTED_FFD_VERSION"
    const val COLUMN_REGISTERED_AGENT_TYPES = "REGISTERED_AGENT_TYPES"
    const val COLUMN_REGISTERED_SUBAGENT_TYPES = "REGISTERED_SUBAGENT_TYPES"
    const val COLUMN_IS_VAT_RATE_20_AVAILABLE = "IS_VAT_RATE_20_AVAILABLE"
    const val COLUMN_IS_DELIVERY_AVAILABLE = "IS_DELIVERY_AVAILABLE"

    @Deprecated("use BASE_URI without PATH_KKT_INFO")
    const val PATH_KKT_INFO = ".Info"
    const val COLUMN_SERIAL_NUMBER = "SERIAL_NUMBER"
    const val COLUMN_REGISTER_NUMBER = "REGISTER_NUMBER"

    const val PATH_KKT_FS_INFO = ".FsInfo"
    const val COLUMN_FS_SERIAL_NUMBER = "SERIAL_NUMBER"

    const val PATH_KKT_FS_REGISTRATION_INFO = ".FsRegistrationInfo"
    const val PATH_KKT_FS_REGISTRATION_INFO_LAST = "LAST"
    const val PATH_KKT_FS_REGISTRATION_INFO_FIRST = "FIRST"
    const val COLUMN_FS_REGISTRATION_INFO_DATE = "DATE"
    const val COLUMN_FS_REGISTRATION_INFO_INN = "INN"
    const val COLUMN_FS_REGISTRATION_INFO_RNM = "RNM"
    const val COLUMN_FS_REGISTRATION_INFO_TAXATION_SYSTEMS = "TAXATION_SYSTEMS"
    const val COLUMN_FS_REGISTRATION_INFO_WORK_MODE_FLAGS = "WORK_MODE_FLAGS"
    const val COLUMN_FS_REGISTRATION_INFO_WORK_MODE_EX_FLAGS = "WORK_MODE_EX_FLAGS"
    const val COLUMN_FS_REGISTRATION_INFO_OFD_INN = "OFD_INN"
    const val COLUMN_FS_REGISTRATION_INFO_REREGISTRATION_REASON_CODE = "REREGISTRATION_REASON_CODE"
    const val COLUMN_FS_REGISTRATION_INFO_FISCAL_DOCUMENT_NUMBER = "FISCAL_DOCUMENT_NUMBER"
    const val COLUMN_FS_REGISTRATION_INFO_FISCAL_DOCUMENT_SIGN = "FISCAL_DOCUMENT_SIGN"

    const val PATH_SESSION_STATUS = ".KktInfoStatus"

    const val COLUMN_SESSION_STATUS_IS_OPEN = "IS_OPEN"
    const val COLUMN_SESSION_STATUS_IS_EXPIRED = "IS_EXPIRED"
    const val COLUMN_SESSION_STATUS_OPEN_DATE = "OPEN_DATE"
    const val COLUMN_SESSION_STATUS_CLOSE_DATE = "CLOSE_DATE"
    const val COLUMN_SESSION_STATUS_SESSION_NUMBER = "SESSION_NUMBER"

    const val PATH_KKT_COUNTERS = ".Counters"
    const val COLUMN_CURRENT_CASH_SUM = "CURRENT_CASH_SUM"
}
