package ru.evotor.framework.receipt

object MedicineAttributeSubTable {
    const val COLUMN_SUBJECT_ID = "SUBJECT_ID"
    const val COLUMN_PREFERENTIAL_MEDICINE_TYPE = "PREFERENTIAL_MEDICINE_TYPE"
    const val COLUMN_MEDICINE_DOCUMENT_NUMBER = "MEDICINE_DOCUMENT_NUMBER"
    const val COLUMN_MEDICINE_DOCUMENT_DATE = "MEDICINE_DOCUMENT_DATE"
    const val COLUMN_MEDICINE_SERIAL_NUMBER = "MEDICINE_SERIAL_NUMBER"
}