package ru.evotor.framework.receipt

object PaymentTable {
    const val COLUMN_UUID = "PAYMENT_UUID"
    const val COLUMN_VALUE = "PAYMENT_VALUE"
    const val COLUMN_PURPOSED_IDENTIFIER = "PAYMENT_PURPOSED_IDENTIFIER"
    const val COLUMN_ACCOUNT_ID = "PAYMENT_ACCOUNT_ID"
    const val COLUMN_ACCOUNT_USER_DESCRIPTION = "PAYMENT_ACCOUNT_USER_DESCRIPTION"
    const val COLUMN_VALUE_BY_PRINT_GROUP = "PAYMENT_VALUE_BY_PRINT_GROUP"
    const val COLUMN_CHANGE_BY_PRINT_GROUP = "PAYMENT_CHANGE_BY_PRINT_GROUP"
}
