package ru.evotor.framework.receipt

object ReceiptHeaderTable {
    const val COLUMN_UUID = "UUID"
    const val COLUMN_BASE_RECEIPT_UUID = "BASE_RECEIPT_UUID"
    const val COLUMN_NUMBER = "NUMBER"
    const val COLUMN_TYPE = "TYPE"
    const val COLUMN_DATE = "DATE"
    const val COLUMN_CLIENT_EMAIL = "CLIENT_EMAIL"
    const val COLUMN_CLIENT_PHONE = "CLIENT_PHONE"
    const val COLUMN_EXTRA = "EXTRA"
    const val COLUMN_SESSION_NUMBER = "SESSION_NUMBER"
    const val COLUMN_RECEIPT_FROM_INTERNET = "RECEIPT_FROM_INTERNET"
    const val COLUMN_PAYMENT_ADDRESS = "PAYMENT_ADDRESS"
    const val COLUMN_PAYMENT_PLACE = "PAYMENT_PLACE"
    const val COLUMN_IS_PAYMENT_INTENT_MODE = "IS_PAYMENT_INTENT_MODE"
    const val COLUMN_PAYMENT_SESSION_ID = "PAYMENT_SESSION_ID"
    const val COLUMN_LOYALTY_CARD_ID = "LOYALTY_CARD_ID"
    const val COLUMN_EXTERNAL_LOYALTY_CARD_ID = "EXTERNAL_LOYALTY_CARD_ID"
    const val COLUMN_ADDITIONAL_DATA = "ADDITIONAL_DATA"
}
